name: "Print Package Version"
description: "Prints the version of the package specified"
outputs:
  version:
    description: "Package Version"
    value: ${{ steps.foo.outputs.version }}
runs:
  using: "composite"
  steps:
    
    - name: List Action Path
      run: ls $GITHUB_ACTION_PATH
      shell: bash
      
    - name: Cache .nuke/temp, ~/.nuget/packages
      uses: actions/cache@v2
      with:
        path: |
          .nuke/temp
          ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
        
    - id: foo
      run: $GITHUB_ACTION_PATH/build.cmd ConfigurePackageVersion
      shell: bash
