name: "Print Package Version"
description: "Prints the version of the package specified"
inputs:
  targetPackagePath:
    description: "Directory with the Package you want to Build"
    required: true
    default: "Packages/your.package.name"
outputs:
  version:
    description: "Package Version"
    value: ${{ steps.foo.outputs.version }}
runs:
  using: "composite"
  steps:
      
    - name: Cache .nuke/temp, ~/.nuget/packages
      uses: actions/cache@v2
      with:
        path: |
          .nuke/temp
          ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
        
    - id: foo
      run: $GITHUB_ACTION_PATH/build.cmd ConfigurePackageVersion --targetPackagePath ${{inputs.targetPackagePath}} --root $GITHUB_ACTION_PATH
      shell: bash
